name: Deploy application

run-name: ${{ github.actor }} is deploying project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-folder:
    name: Create folder on server
    runs-on: ubuntu-latest
    steps:
      - name: Create remote directory via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /opt/ms-clinique-rabat/microservices

  build-project:
    name: Build & deploy Spring Boot application
    runs-on: ubuntu-latest
    needs: create-folder
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Make mvnw executable
        working-directory: springBoot
        run: chmod +x mvnw

      - name: Build Spring Boot project
        working-directory: springBoot
        run: |
          ./mvnw clean package -DskipTests
          ls -lh target

      - name: Copy JAR to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: springBoot/target/GestionClinique-0.0.1-SNAPSHOT.jar
          target: /opt/ms-clinique-rabat/microservices/
          overwrite: true

  run-project:
    name: Create folder on server
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Run application via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ln -sf /opt/ms-clinique-rabat/microservices/GestionClinique-0.0.1-SNAPSHOT.jar /etc/init.d/ms-clinique-rabat
            /etc/init.d/ms-clinique-rabat stop || true
            /etc/init.d/ms-clinique-rabat start \
              --spring.mail.host=${{ secrets.MAIL_HOST }} \
              --spring.datasource.username=${{ secrets.DATABASE_USERNAME }} \
              --spring.datasource.password=${{ secrets.DATABASE_USERPASSWORD }} \
              --spring.datasource.url=${{ secrets.DATABASE_URL }} \
              --spring.sql.init.mode=true
